[package]
name = "wootheex_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "wootheex_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.1"
lazy_static = "1.0"
woothee = "^0"

[build]
target = "x86_64-unknown-linux-musl"
